---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - math.example.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - math.example.com
  resources:
  - adds
  - httptasks
  - squares
  - subtracts
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.example.com
  resources:
  - adds/finalizers
  - httptasks/finalizers
  - squares/finalizers
  - subtracts/finalizers
  verbs:
  - update
- apiGroups:
  - math.example.com
  resources:
  - adds/status
  - httptasks/status
  - squares/status
  - subtracts/status
  - workflows/status
  verbs:
  - get
  - patch
  - update
