---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - math.example.com
  resources:
  - adds
  - squares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - math.example.com
  resources:
  - adds/finalizers
  - squares/finalizers
  verbs:
  - update
- apiGroups:
  - math.example.com
  resources:
  - adds/status
  - squares/status
  verbs:
  - get
  - patch
  - update
