apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: httptask-generic
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-tasks
    functionRef:
      name: function-httptask