apiVersion: example.crossplane.io/v1
kind: Workflow
metadata:
  name: example-xr
spec:
  notifyURL: https://webhook.site/dba616f8-4834-4d2b-a7a6-85a23a830fda
  tasks:
  - name: add
    endpoint: http://mock-server.default.svc.cluster.local:9090/add
    input:
      x: 5
      "y": 7
  - name: square
    endpoint: http://mock-server.default.svc.cluster.local:9090/square
    inputFrom:
    - sourceTask: add
      sourceField: sum
      targetField: value